@startsalt
'https://plantuml.com/salt
{
!theme mimeograph
  **Previsualizacion**
  [Editar <&pencil>]
  Plantilla #1
    | - Sección 1
    | --
    | {Título: | " Datos generales"}
    {
      Nombre: | {"Natalio Reyes Colás"}
      <color:#9a9a9a>Obligatoria
    }
    {
      Fecha: | {"20/02/2023"|<&calendar>}
      <color:#9a9a9a> Obligatoria
    }
    {
      Sexo: | {(X) masculino|() femenino}
      <color:#9a9a9a> Obligatoria
      }
'    | {T!
'
'        sd
'        }
    | --
    + Sección 2
    + Sección 3
}
@endsalt
