@startuml
(*) --> "
{{
  salt
  {
    <b> click en agregar nueva pregunta
    {+

      **Modo Edición**
      [Previsualizar <&eye>]
      Plantilla #1
        | - Sección 1 | [Eliminar sección]
        | --
        | {Título: | " Datos generales"}
        {+
          Nombre: | {"Natalio Reyes Colás"}
          [X]Obligatoria
        }|[Eliminar pregunta]
        {+
          Fecha: | {"20/02/2023"|<&calendar>}
          [X]Obligatoria
        }|[Eliminar pregunta]
        {+
          Sexo: | {(X) masculino|() femenino}
          [X]Obligatoria
         }|[Eliminar pregunta]
        | [Agregar pregunta]
        | --
        + Sección 2
        + Sección 3
        [Agregar sección]
      }
     }
  }
}}
" as add

add -right-> "
{{
  salt
  {
     <b> seleccionar tipo de pregunta
     {+
      **Agregar nueva pregunta**
      ---|--
      Seleccione el tipo de pregunta: | ^PreguntaAbierta^Pregunta de Fecha^Pregunta de Opcion multiple^
    }
   }
}}
" as choose

choose --> "
{{
  salt
  {
     <b> pregunta abierta
     {+
      **Agregar nueva pregunta**
      ---|--
      Seleccione el tipo de pregunta: | ^PreguntaAbierta^
      {+
        Nombre del campo: | {"Nombre:"}
        [X]Obligatoria
      }
    }
   }
}}
" as open

choose --> "
{{
  salt
  {
     <b> pregunta de fecha
     {+
      **Agregar nueva pregunta**
      ---|--
      Seleccione el tipo de pregunta: | ^Pregunta de Fecha^
      {+
        Nombre del campo: | {"Fecha de Nacimiento:"}
        [X]Obligatoria
      }
    }
   }
}}
" as date
choose --> "
{{
  salt
  {
     <b> pregunta de opcion multiple
     {+
      **Agregar nueva pregunta**
      ---|--
      Seleccione el tipo de pregunta: | ^Pregunta de Opcion multiple^
      {+
        Nombre del campo: | {"Sexo:"}
        [Agregar opcion]
        valor:|"masculino"|[Eliminar]
        valor:|"femenino"|[Eliminar]
        [X]Obligatoria
      }
    }
   }
}}
" as mutipleoption
@enduml
