@startsalt
'https://plantuml.com/salt
{
!theme mimeograph
  **Modo Edición**
  [Previsualizar <&eye>]
  Plantilla #1
    | - Sección 1 | [Eliminar sección]
    | --
    | {Título: | " Datos generales"}
    {+
      Nombre del campo: | {"Nombre:"}
      [X]Obligatoria
    }|[Eliminar pregunta]
    {+
      Nombre del campo: | {"Fecha de Nacimiento:"}
      [X]Obligatoria
    }|[Eliminar pregunta]
    {+
      Nombre del campo: | {"Sexo:"}
      [Agregar opcion]
      valor:|"masculino"|[Eliminar]
      valor:|"femenino"|[Eliminar]
      [X]Obligatoria
    }|[Eliminar pregunta]
'    | {T!
'
'        sd
'        }
    | [Agregar pregunta]
    | --
    + Sección 2
    + Sección 3
    [Agregar sección]
}
@endsalt
